### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 0xlance** [Dheerajmadhukar/karma_v1#1]
I got the below error when i tried to run the script :
"
Error: Invalid value for "filenames": Path "facebook.com.json.gz" does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.9.5', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.6/dist-packages/Interlace-1.9.5-py3.6.egg/Interlace/interlace.py", line 41, in main
  File "/usr/local/lib/python3.6/dist-packages/Interlace-1.9.5-py3.6.egg/Interlace/lib/threader.py", line 101, in __init__
  File "/usr/local/lib/python3.6/dist-packages/Interlace-1.9.5-py3.6.egg/Interlace/interlace.py", line 11, in task_queue_generator_func
  File "/usr/local/lib/python3.6/dist-packages/Interlace-1.9.5-py3.6.egg/Interlace/lib/core/input.py", line 264, in process_data_for_tasks_iterator
Exception: No target provided, or empty target list

"

**Comment by Dheerajmadhukar** [comment]
It happened when no data found. 

Fix:

Update with more dorks & validation input

Now you can update it using : git pull ;)
