### ISSUE TITLE
JSON format

### ISSUE THREAD

**Issue by emadshanab** [Dheerajmadhukar/karma_v1#3]
Hello bro.
Thanks for your great job.
Could you please change the output from json to txt  and just save the url to be easy scanning via nmap or httpx.
Thanks.

**Comment by Dheerajmadhukar** [comment]
Text file are available : 

IPs : output/target.tld-YYY-MM-DD/ips_inscope.txt
URLs: output/target.tld-YYY-MM-DD/curl_issuer_target.data
Raw Data: output/target.tld-YYY-MM-DD/main_target.data

**Comment by Dheerajmadhukar** [comment]
Thanks mate, i realized that the script only produce JSON output. Its fixed. Please check :) My bad !

**Comment by emadshanab** [comment]
Thanks mate, i got this error now

bash karma_v1 google.com



--------------------------------
Usage: shodan parse [OPTIONS] <filenames>

Error: Invalid value for "filenames": Path "/root/Desktop/karma_v1/output/google.com-2021-08-01/*.json.gz" does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.9.5', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.5-py3.8.egg/Interlace/interlace.py", line 36, in main
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.5-py3.8.egg/Interlace/lib/threader.py", line 101, in __init__
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.5-py3.8.egg/Interlace/interlace.py", line 11, in task_queue_generator_func
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.5-py3.8.egg/Interlace/lib/core/input.py", line 264, in process_data_for_tasks_iterator
Exception: No target provided, or empty target list

**Comment by Dheerajmadhukar** [comment]
I did the same, getting results:

# bash karma_v1 google.com

Saved 1000 results into file  output/google.com-2021-08-01/ssl_domain_google.com.json.gz
Saved 1000 results into file  output/google.com-2021-08-01/ssl_issuer_google.com.json.gz
.
.
Do check one more time. If you will face the same problem, please ping me on twitter :)
